# Site settings
title: Noel the Spark
email: info@noelthespark.co.uk
description: "NTS Electrical Services. Are you in need of a time served 24hr Emergency Electrician in Newtownabbey? For a full range of electrical services call us now."
baseurl: ""
url: "http://www.noelthespark.co.uk"

# Build settings
markdown: kramdown
permalink: none
